# Generated by Django 2.2.2 on 2022-09-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_entidades_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='entidad_opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=120)),
                ('opcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='entidades_solicitud',
        ),
        migrations.DeleteModel(
            name='opciones',
        ),
    ]
