# Generated by Django 2.2.2 on 2022-09-07 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('num_preguntas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120, unique=True)),
                ('quizros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Quizros')),
            ],
        ),
        migrations.CreateModel(
            name='answ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cuest')),
                ('quizros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Quizros')),
            ],
            options={
                'unique_together': {('question', 'text')},
            },
        ),
    ]
