# Generated by Django 2.2.2 on 2022-09-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuest',
            name='tipoPregunta',
            field=models.CharField(choices=[('UNA', 'UNA'), ('MULTIPLE', 'MULTIPLE'), ('ABIERTA', 'ABIERTA')], default='UNA', max_length=20),
        ),
    ]
