# Generated by Django 2.2.2 on 2022-09-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_answ_correct_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answ',
            name='correct_n',
        ),
    ]
