# Generated by Django 2.2.2 on 2022-09-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_cuest_correcta_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuest',
            name='correcta_n',
            field=models.IntegerField(default=1),
        ),
    ]
