# Generated by Django 2.2.2 on 2022-10-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20220927_1240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuest',
            unique_together={('question', 'quizros')},
        ),
    ]
