# Generated by Django 2.2.2 on 2022-09-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='efectivo',
            name='TransaccionValor',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
