# Generated by Django 2.2.2 on 2022-09-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_efectivo_transaccionvalor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efectivo',
            name='TransaccionValor',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
