# Generated by Django 2.2.2 on 2022-09-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_auto_20220926_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efectivo',
            name='TransaccionValor',
        ),
    ]
