# Generated by Django 2.2.2 on 2022-11-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_auto_20221121_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambiarias',
            name='paisDestino',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
