# Generated by Django 2.2.2 on 2022-11-21 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_auto_20221121_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cambiarias',
            old_name='valorTran_char',
            new_name='TransaccionValor',
        ),
    ]
