# Generated by Django 2.2.2 on 2022-11-21 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0009_auto_20221121_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaracionrenta',
            old_name='gastos_char',
            new_name='gasto',
        ),
        migrations.RenameField(
            model_name='declaracionrenta',
            old_name='ingresoBruto_char',
            new_name='ingreso_Bruto',
        ),
        migrations.RenameField(
            model_name='declaracionrenta',
            old_name='ingresoLiquido_char',
            new_name='ingreso_Liquido',
        ),
        migrations.RenameField(
            model_name='declaracionrenta',
            old_name='pasivo_char',
            new_name='pasivos',
        ),
        migrations.RenameField(
            model_name='declaracionrenta',
            old_name='patrimonioBruto_char',
            new_name='patrimonio_Bruto',
        ),
        migrations.RenameField(
            model_name='declaracionrenta',
            old_name='patrimonioLiquido_char',
            new_name='patrimonio_Liquido',
        ),
    ]
