# Generated by Django 2.2.2 on 2022-11-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0011_auto_20221121_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroros',
            name='Valor_Operacion',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
