# Generated by Django 2.2.2 on 2022-11-21 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0012_registroros_valor_operacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroros',
            name='fechaFinalOperacion',
        ),
        migrations.RemoveField(
            model_name='registroros',
            name='fechaInicialOperacion',
        ),
    ]
