# Generated by Django 2.2.2 on 2022-11-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0014_efectivo_valor_transaccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actosnotariales',
            old_name='nombreNotaria',
            new_name='escribanos',
        ),
        migrations.AddField(
            model_name='actosnotariales',
            name='Valor_Transaccion',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
