# Generated by Django 2.2.2 on 2023-10-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0016_efectivo_ros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efectivo',
            name='ros',
            field=models.IntegerField(default=0),
        ),
    ]
