# Generated by Django 2.2.2 on 2023-11-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0019_confecamaras_ros'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambiarias',
            name='ros',
            field=models.IntegerField(default=0),
        ),
    ]
