# Generated by Django 2.2.2 on 2023-11-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0021_productos_ros'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='noProducto',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
