# Generated by Django 2.2.2 on 2023-11-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0022_productos_noproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroros',
            name='ros',
            field=models.IntegerField(default=0),
        ),
    ]
