# Generated by Django 2.2.2 on 2023-11-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0023_registroros_ros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroros',
            name='codigoROS',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
