# Generated by Django 2.2.2 on 2023-11-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0024_auto_20231116_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroros',
            name='descripcionOperacion',
            field=models.TextField(max_length=4000),
        ),
    ]
