# Generated by Django 2.2.2 on 2023-11-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0025_auto_20231116_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroros',
            name='descripcionOperacion',
            field=models.TextField(max_length=6000),
        ),
    ]
