# Generated by Django 2.2.2 on 2023-11-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0026_auto_20231116_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='actosnotariales',
            name='ros',
            field=models.IntegerField(default=0),
        ),
    ]
