# Generated by Django 2.2.2 on 2023-11-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0027_actosnotariales_ros'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguridadSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoid', models.CharField(max_length=20)),
                ('idBeneficiario', models.IntegerField(default=0)),
                ('edadBeneficiario', models.IntegerField(default=0)),
                ('calidadBeneficiario', models.CharField(max_length=20)),
                ('tipoIdTitular', models.CharField(max_length=20)),
                ('idTitular', models.IntegerField(default=0)),
                ('nombreTitular', models.CharField(max_length=20)),
                ('edadTitular', models.IntegerField(default=0)),
                ('ros', models.IntegerField(default=0)),
                ('nombreBeneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombreBeneficiario', to='consultas.Personas')),
            ],
        ),
    ]
