# Generated by Django 2.2.2 on 2022-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='textros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('anexo', models.TextField()),
            ],
        ),
    ]
