# Generated by Django 2.2.2 on 2022-09-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ros', '0002_textros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextoROS',
        ),
    ]
