# Generated by Django 2.2.2 on 2023-09-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ros', '0003_delete_textoros'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='staticfiles/')),
            ],
        ),
    ]
