# Generated by Django 2.2.2 on 2023-09-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ros', '0004_postros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postros',
            name='title',
            field=models.FileField(upload_to=''),
        ),
    ]
