# Generated by Django 2.2.2 on 2023-09-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ros', '0005_auto_20230907_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postros',
            name='title',
            field=models.TextField(),
        ),
    ]
