# Generated by Django 2.2.2 on 2023-09-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ros', '0007_auto_20230907_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postros',
            name='image',
            field=models.FileField(blank=True, upload_to='staticfiles/'),
        ),
    ]
