# Generated by Django 2.2.2 on 2023-09-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ros', '0008_auto_20230907_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='postros',
            name='image2',
            field=models.FileField(blank=True, upload_to='static/'),
        ),
    ]
